sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.4
  - jruby
  - rbx-3
  - ree
  - ruby-head
matrix:
  allow_failures:
    rvm:
      - ruby-head
      - ree
      - rbx-3

before_install:
  - gem update --system
  - gem --version
